version: '3.9'

services:
  devnet:
    container_name: geth
    image: afidosiev/geth:latest_contracts
    command: --dev --http --http.addr 0.0.0.0 --datadir /root/.ethereum --dev.period 12 --http.vhosts=* --ws --ws.addr 0.0.0.0 --http.api eth,net,web3,debug,txpool --ws.api eth,net,web3,debug,txpool
    ports:
      - 8545:8545
      - 8546:8546
